trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build First Build Completed.
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash:  java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    
  # - job: SecondJob
  #   steps: 
  #   - bash: echo build Second Job Completed.
# - stage: DevDeploy
#   variables:
#     environments: QA
#   dependsOn: Build
#   jobs:
#   - job:
#     steps: 
#     - bash: echo $(environment)DeployJob. 
# - stage: QADeploy
#   dependsOn: DevDeploy
#   jobs:
#   - job:
#     steps: 
#     - bash: echo $(environment)DeployJob. 
# - stage: ProdDeployJob
#   dependsOn: QADeploy
#   jobs:
#   - job:
#     steps: 
#     - bash: echo $(environment)DeployJob. 

